[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_ENABLED = false
  SECRETS_SCAN_OMIT_PATHS = ".env.example,classroom_web_credentials.json,google_credentials.json,*.md,package*.json"

[build.processing]
  skip_processing = false
