[build]
  command = "npm run build"
  publish = "dist"

# Omitir archivos del escaneo de secretos
[build.environment]
  SECRETS_SCAN_OMIT_PATHS = ".env.example,classroom_web_credentials.json,google_credentials.json"
